version: '3.8'

services:
  postgres:
    image: postgres:13
    ports: 
      - "5433:5432"
    environment:
      POSTGRES_DB: traveldb
      POSTGRES_USER: traveluser
      POSTGRES_PASSWORD: travelpass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U traveluser -d traveldb"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: