version: '3'

services:
  postgres:
    image: postgres:13
    ports: 
      - "5433:5432"
    environment:
      POSTGRES_DB: traveldb
      POSTGRES_USER: traveluser
      POSTGRES_PASSWORD: travelpass
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: